config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "prototypes#index"

  get 'prototypes', to: 'prototypes#index'
  resources :prototypes, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :users, only: [:show]

  as :user do
    get '/users/sign_out', to: 'devise/sessions#destroy', as: :logout
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user # ユーザーとの関連付け
  belongs_to :prototype # プロトタイプとの関連付け
end

app/models/prototype.rb
class Prototype < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :comments

  validates :title, presence: true
  validates :catch_copy, presence: true
  validates :concept, presence: true
  validate :validate_image_presence

  private

  def validate_image_presence
    errors.add(:image, "must be attached") unless image.attached?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         validates :name, presence: true
         validates :profile, presence: true
         validates :occupation, presence: true
         validates :position, presence: true
  has_many :prototypes
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Deviseコントローラーの場合に許可されるパラメーターを設定
  before_action :configure_permitted_parameters, if: :devise_controller?

  # アクティブストレージのURLオプションを設定
  before_action :set_url_options

  private

  # Deviseで許可されるパラメーターを設定
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation, :name, :profile, :occupation, :position])
  end

  # アクティブストレージのURLオプションを設定
  def set_url_options
    ActiveStorage::Current.url_options = Rails.application.routes.default_url_options
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_prototype, only: [:show]

  def index
    @prototypes = Prototype.all
  end

  def show
    # before_action でセットされているので、ここでは不要
  end

  def new
    @prototype = Prototype.new
  end

  def create
    @prototype = current_user.prototypes.build(prototype_params.merge(user_id: current_user.id))
    if @prototype.save
      redirect_to root_path, notice: 'Prototype was successfully created.'
    else
      render :new
    end
  end

  private

  def set_prototype
    @prototype = Prototype.find(params[:id])
  end

  def prototype_params
    params.require(:prototype).permit(:title, :catch_copy, :concept, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Protospace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <% if user_signed_in? %>  <!-- ログインしている場合の処理 -->
         <div class="nav__right">
          <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: 'btn'%>
          <%= link_to "New Proto", new_prototype_path, class: :nav__btn %>
         </div>
         <% else %> <!-- ログインしていない場合 -->
            <div class="nav__right">
             <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
             <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
            <% end %>
          <%# ログインしているときは以下を表示するようにしましょう %>
            <%# <div class="nav__right"> %>
              <%# <%= link_to "ログアウト", root_path, class: :nav__logout %>
              <%# <%= link_to "New Proto", root_path, class: :nav__btn %>
            <%# </div> %>
          <%# // ログインしているときは上記を表示するようにしましょう %>
          
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © PROTO SPACE All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/prototypes/_form.html.erb
<%= form_with(model: @prototype, local: true) do |f| %>
  <div class="field">
    <%= f.label :title, "プロトタイプの名称" %><br />
    <%= f.text_field :title, id: "prototype_title" %>
  </div>

  <div class="field">
    <%= f.label :catch_copy, "キャッチコピー" %><br />
    <%= f.text_area :catch_copy, class: :form__text, id: "prototype_catch_copy" %>
  </div>

  <div class="field">
    <%= f.label :concept, "コンセプト" %><br />
    <%= f.text_area :concept, class: :form__text, id: "prototype_concept" %>
  </div>

  <div class="field">
    <%= f.label :image, "プロトタイプの画像" %><br />
    <%= f.file_field :image, id: "prototype_image" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/prototypes/_prototype.html.erb
<div class="card">
  <%= link_to prototype_path(prototype) do %>
    <%= image_tag prototype.image, class: 'prototype-image' if prototype.image.attached? %>
  <% end %>
  <h2><%= link_to prototype.title, prototype_path(prototype) %></h2>
  <p><%= prototype.catch_copy %></p>
  <p>投稿者: <%= prototype.user.name %></p>
</div>

app/views/prototypes/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">プロトタイプ編集</h2>
      <%# 部分テンプレートでフォームを表示する %>
    </div>
  </div>
</div>

app/views/prototypes/index.html.erb
<main class="main">
  <div class="inner">
    
    <% if user_signed_in? %>
      <div class="greeting">
        こんにちは、<%= link_to current_user.name, root_path, class: :greeting__link %>
      </div>
    <% end %>
      
    <div class="card__wrapper">
      <%= render partial: 'prototype', collection: @prototypes %>
    </div>
  </div>
</main>

app/views/prototypes/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規プロトタイプ投稿</h2>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/prototypes/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @prototype.title %>
      </p>
      <%= link_to "by #{@prototype.user.name}", user_path(@prototype.user), class: :prototype__user %>
      <%# プロトタイプの投稿者とログインしているユーザーが同じであれば以下を表示する %>
      <% if user_signed_in? && current_user == @prototype.user %>
        <div class="prototype__manage">
          <%= link_to "編集する", edit_prototype_path(@prototype), class: :prototype__btn %>
          <%= link_to "削除する", prototype_path(@prototype), method: :delete, data: { confirm: "本当に削除しますか？" }, class: :prototype__btn %>
        </div>
      <% end %>
      <%# // プロトタイプの投稿者とログインしているユーザーが同じであれば上記を表示する %>
      <div class="prototype__image">
        <%= image_tag @prototype.image if @prototype.image.attached? %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">キャッチコピー</p>
          <p class="detail__message">
            <%= @prototype.catch_copy %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">コンセプト</p>
          <p class="detail__message">
            <%= @prototype.concept %>
          </p>
        </div>
      </div>
      <div class="prototype__comments">
        <%# ログインしているユーザーには以下のコメント投稿フォームを表示する %>
        <% if user_signed_in? %>
          <%= render 'prototypes/form', prototype: @prototype %>
        <% end %>
        <%# // ログインしているユーザーには上記を表示する %>
        <ul class="comments_lists">
          <%# 投稿に紐づくコメントを一覧する処理を記述する %>
          <% @prototype.comments.each do |comment| %>
            <li class="comments_list">
              <%= comment.content %>
              <%= link_to "(#{comment.user.name})", user_path(comment.user), class: :comment_user %>
            </li>
          <% end %>
          <%# // 投稿に紐づくコメントを一覧する処理を記述する %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "ユーザー名さんの情報"%>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= "ユーザー名" %></td>
          </tr>
          <tr>
            <th class="table__col1">プロフィール</th>
            <td class="table__col2"><%= "ユーザーのプロフィール" %></td>
          </tr>
          <tr>
            <th class="table__col1">所属</th>
            <td class="table__col2"><%= "ユーザーの所属" %></td>
          </tr>
          <tr>
            <th class="table__col1">役職</th>
            <td class="table__col2"><%= "ユーザーの役職" %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "ユーザー名さんのプロトタイプ"%>
      </h2>
      <div class="user__card">
        <%# 部分テンプレートでそのユーザーが投稿したプロトタイプ投稿一覧を表示する %>
      </div>
    </div>
  </div>
</div>